### ISSUE TITLE
is it normal that the emojis are not shown in the commit message ?

### ISSUE THREAD

**Issue by kariae** [pvdlg/conventional-changelog-metahub#58]

**Comment by pvdlg** [comment]
I can't really help with just a one liner in the issue title. Please provide context and details.

**Comment by kariae** [comment]
ah sorry Pierre, I'm trying to use a commit analyzer adapter to create commit comments with emojis, and I think I opened the issue in the wrong repo, the adapter I'm trying to use is `[@metahub/cz-conventional-commit](https://www.npmjs.com/package/@metahub/cz-conventional-commit)` and the commit message generated was not containing the emoji type.

sorry again, I think you can close the issue :)
